# Generated by Django 3.2.5 on 2021-08-25 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('doctorId', models.PositiveIntegerField(null=True)),
                ('doctorName', models.CharField(max_length=40, null=True)),
                ('patientName', models.CharField(max_length=40, null=True)),
                ('appointmentDate', models.DateField(auto_now=True)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'balanta',
            },
        ),
        migrations.CreateModel(
            name='instructions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='instructions/%y')),
            ],
        ),
        migrations.CreateModel(
            name='laboratorist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/DoctorProfilePic/')),
                ('address', models.CharField(choices=[('hargeisa', 'hargeisa'), ('borama', 'borama'), ('gabilay', 'gabilay'), ('burco', 'burco'), ('ceerigabo', 'ceerigabo'), ('odwayne', 'odwayne'), ('saylac', 'saylac'), ('caynabo', 'caynabo'), ('laascanod', 'laascanod'), ('arabsiyo', 'arabsiyo'), ('oodwayne', 'oodwayne'), ('barbara', 'barbara'), ('magaalo kale', 'magaalo kale')], default='hargeisa', max_length=50)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('test', models.CharField(choices=[('blood', 'blood'), ('urine', 'urine')], default='blood', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='massages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('by', models.CharField(default='hospitl', max_length=20, null=True)),
                ('message', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'fariimaha',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/PatientProfilePic/')),
                ('age', models.IntegerField(default=18)),
                ('address', models.CharField(choices=[('hargeisa', 'hargeisa'), ('borama', 'borama'), ('gabilay', 'gabilay'), ('burco', 'burco'), ('ceerigabo', 'ceerigabo'), ('odwayne', 'odwayne'), ('saylac', 'saylac'), ('caynabo', 'caynabo'), ('laascanod', 'laascanod'), ('arabsiyo', 'arabsiyo'), ('oodwayne', 'oodwayne'), ('barbara', 'barbara'), ('magaalo kale', 'magaalo kale')], default='hargeisa', max_length=50)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('assignedDoctorId', models.PositiveIntegerField(null=True)),
                ('admitDate', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='PatientDischargeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('patientName', models.CharField(max_length=40)),
                ('assignedDoctorName', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('symptoms', models.CharField(max_length=100, null=True)),
                ('diagnosis', models.CharField(max_length=100, null=True)),
                ('treatment', models.CharField(max_length=100, null=True)),
                ('medicne', models.CharField(max_length=100, null=True)),
                ('admitDate', models.DateField()),
                ('releaseDate', models.DateField()),
                ('daySpent', models.PositiveIntegerField()),
                ('roomCharge', models.PositiveIntegerField()),
                ('medicineCost', models.PositiveIntegerField()),
                ('doctorFee', models.PositiveIntegerField()),
                ('OtherCharge', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'discharge',
            },
        ),
        migrations.CreateModel(
            name='treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.CharField(max_length=100, null=True)),
                ('diagnosis', models.CharField(max_length=100, null=True)),
                ('treatment', models.CharField(default='nasasho', max_length=100)),
                ('medicne', models.CharField(max_length=100, null=True)),
                ('patientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
            options={
                'db_table': 'daawada',
            },
        ),
        migrations.CreateModel(
            name='shaybaadh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testname', models.CharField(max_length=50)),
                ('labaratorist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.laboratorist')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
            options={
                'db_table': 'shaybaadh',
            },
        ),
        migrations.CreateModel(
            name='patientstatu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('inpatient', 'inpatient'), ('outpatient', 'oupatient')], max_length=50)),
                ('relations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
        migrations.CreateModel(
            name='khaas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('by', models.CharField(default='hospital', max_length=50, null=True)),
                ('message', models.CharField(max_length=500)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/DoctorProfilePic/')),
                ('address', models.CharField(choices=[('hargeisa', 'hargeisa'), ('borama', 'borama'), ('gabilay', 'gabilay'), ('burco', 'burco'), ('ceerigabo', 'ceerigabo'), ('odwayne', 'odwayne'), ('saylac', 'saylac'), ('caynabo', 'caynabo'), ('laascanod', 'laascanod'), ('arabsiyo', 'arabsiyo'), ('oodwayne', 'oodwayne'), ('barbara', 'barbara'), ('magaalo kale', 'magaalo kale')], default='hargeisa', max_length=50)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(choices=[('dhaqtarka indhaha', 'optometrist'), ('cardiologist', 'dhaqtarka wadnaha'), ('Dermatologists', 'dhaqtarka maqaarka'), ('Emergency Medicine Specialists', 'dhaqtarka xaalad dagdag ah'), ('Allergists/Immunologists', 'dhaqtarka alarjiga'), ('Anesthesiologists', 'dhaqtarka suuxdinta')], default='optometrist', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
    ]
